# Generated by Django 2.1.2 on 2018-10-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoundTable', '0002_teammod_useraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammod',
            name='slug',
        ),
    ]
