# Generated by Django 2.1.2 on 2018-10-23 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RoundTable', '0003_remove_teammod_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammod',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammod',
            name='team_name',
            field=models.CharField(max_length=30, verbose_name='Название пространсва'),
        ),
    ]
