# Generated by Django 2.1.2 on 2018-10-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoundTable', '0004_auto_20181023_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammod',
            name='slug',
        ),
    ]
