# Generated by Django 2.1.2 on 2018-10-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoundTable', '0005_remove_teammod_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammod',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=30, verbose_name='Название пространсва'), max_length=30),
        ),
    ]
