# Generated by Django 2.1.2 on 2018-10-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoundTable', '0006_teammod_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammod',
            name='slug',
            field=models.SlugField(max_length=30),
        ),
    ]
