# Generated by Django 2.1.2 on 2018-10-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoundTable', '0007_auto_20181023_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='teams',
            field=models.ManyToManyField(blank=True, to='RoundTable.TeamMod'),
        ),
    ]
