# Generated by Django 2.1.2 on 2018-10-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoundTable', '0009_auto_20181025_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammod',
            name='team',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='teams',
            field=models.ManyToManyField(blank=True, to='RoundTable.TeamMod'),
        ),
    ]
