# Generated by Django 2.1.2 on 2018-11-04 16:15

import RoundTable.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoundTable', '0011_auto_20181026_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='RoundTable/default_avatar/default.png', upload_to=RoundTable.models.User.avatar_upload_to, verbose_name='Аватар'),
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
