# Generated by Django 2.1.2 on 2018-11-04 21:27

import RoundTable.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoundTable', '0012_auto_20181104_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='RoundTable/default_avatar/default.png', upload_to=RoundTable.models.User.avatar_upload_to, verbose_name='Аватар'),
        ),
    ]
