# Generated by Django 2.1.2 on 2018-11-04 22:57

import RoundTable.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoundTable', '0013_auto_20181105_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=RoundTable.models.User.avatar_upload_to, verbose_name='Аватар'),
        ),
    ]
