# Generated by Django 2.1.2 on 2018-11-24 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoundTable', '0017_auto_20181108_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='username_from',
        ),
        migrations.AddField(
            model_name='invite',
            name='user_from',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invite',
            name='user_for',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
