# Generated by Django 2.1.2 on 2018-11-24 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RoundTable', '0018_auto_20181125_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
