# Generated by Django 2.1.2 on 2018-11-25 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoundTable', '0021_auto_20181125_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='time',
        ),
        migrations.AddField(
            model_name='invite',
            name='date_sand',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user',
            name='date_creation',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
