# Generated by Django 2.1.2 on 2018-11-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoundTable', '0022_auto_20181125_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='date_sand',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
